copisteria: cliente.c proxy.c servidor.c 
	gcc -o ./papelera/cliente cliente.c
	gcc -o ./papelera/proxy proxy.c
	gcc -o ./papelera/servidor servidor.c
	./papelera/servidor 

# ejecutar desde otra terminal: ./papelera/cliente <nombre_fifo> <numero clientes>
# ejemplo: ./papelera/cliente /papelera/fifo 5

