prueba:  
	gcc preuba.c -o ./papelera/prueba

tarea9:  
	gcc tarea9.c -o ./papelera/tarea9
	./papelera/tarea9

tarea10:  
	gcc tarea10.c -o ./papelera/tarea10
	./papelera/tarea10

tarea11:  
	gcc tarea11.c -o ./papelera/tarea11
	./papelera/tarea11 

ejercicio1: ./ejercicio1/envioSignal.c ./ejercicio1/reciboSignal.c
	gcc ./ejercicio1/envioSignal.c -o ./papelera/envioSignal
	gcc ./ejercicio1/reciboSignal.c -o ./papelera/reciboSignal
	./papelera/reciboSignal & 

ejercicio2: ./ejercicio2.c
	gcc ./ejercicio2.c -o ./papelera/ejercicio2
	./papelera/ejercicio2 &
	ps

ejercicio3: ./ejercicio3.c
	gcc ./ejercicio3.c -o ./papelera/ejercicio3
	./papelera/ejercicio3 

ejercicio4: ./ejercicio4.c
	gcc ./ejercicio4.c -o ./papelera/ejercicio4
	./papelera/ejercicio4

