
ejercicio1: ejercicio1.c
	gcc ejercicio1.c -o ./papelera/ejercicio1
	./papelera/ejercicio1 10

ejercicio2: ejercicio2.c
	gcc ejercicio2.c -o ./papelera/ejercicio2
	./papelera/ejercicio2 

ejercicio3: ejercicio3.c
	gcc ejercicio3.c -o ./papelera/ejercicio3
	./papelera/ejercicio3 

ejercicio4: ejercicio4.c
	gcc ejercicio4.c -o ./papelera/ejercicio4
	./papelera/ejercicio4

ejercicio5: ejercicio5.c
	gcc ejercicio5.c -o ./papelera/ejercicio5
	./papelera/ejercicio5

ejercicio6: ejercicio6.c
	gcc ejercicio6.c -o ./papelera/ejercicio6
	./papelera/ejercicio6	

ejercicio7: ejercicio7.c
	gcc ejercicio7.c -o ./papelera/ejercicio7
	./papelera/ejercicio7 ls 
	./papelera/ejercicio7 ls -l -a
	./papelera/ejercicio7 ls -l -a bg

prueba3: prueba3.c
	gcc prueba3.c -o ./papelera/prueba3
	./papelera/prueba3 1 2 3 4 1



clean:
	rm -f ./papelera/*

