ejercicio1:
	gcc ejercicio1.c -o ./papelera/ejercicio1
	echo "gato\nperro\nmanzana\nzanahoria\nelefante\nuva" > ./papelera/texto_ejemplo.txt
	./papelera/ejercicio1 sort "<" ./papelera/texto_ejemplo.txt
	./papelera/ejercicio1 ls ">" ./papelera/texto_ejemplo.txt

ejercicio2:
	gcc ejercicio2.c -o ./papelera/ejercicio2
	./papelera/ejercicio2 ls "|" sort

ejercicio3:
	gcc ejercicio3.c -o ./papelera/ejercicio3
	./papelera/ejercicio3 

tarea14:
	gcc tarea14.c -o ./papelera/tarea14
	./papelera/tarea14

tarea15:
	gcc tarea15.c -o ./papelera/tarea15
	./papelera/tarea15 ./papelera/archivo1.txt 5

tarea16:
	gcc tarea16.c -o ./papelera/tarea16
	./papelera/tarea16 

ejercicio5:
	gcc ejercicio5.c -o ./papelera/ejercicio5
	./papelera/ejercicio5 ./papelera/archivo1.txt ./papelera/archivo1_copia.txt